version: '3.7'

networks:
  learning-golang:
    name: learning-golang
    external: true

services:
  app:
    build:
      context: .
      dockerfile: ./docker/DockerFile
    ports:
      - "6000"
    networks:
      - learning-golang
    volumes:
      - ./src:/src/